apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis5
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: redis5
    spec:
      containers:
      - name: redis5
        image: redislabs/redis:5.0.0-31
        ports:
        - containerPort: 8001
        - containerPort: 7443
        - containerPort: 9443
        securityContext:
          capabilities:
            add:
              - SYS_RESOURCE

---
apiVersion: v1
kind: Service
metadata:
  name: redis5
  labels:
    app: redis5
spec:
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30030
    protocol: TCP
    name: sentinal
  - port: 7443
    targetPort: 7443
    nodePort: 30040
    protocol: TCP
    name: ui
  - port: 9443
    targetPort: 9443
    nodePort: 30050
    protocol: TCP
    name: api
  type: NodePort
  selector:
    app: redis5